[package]
name = "farm-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"]}
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"

[dependencies.image]
version = "0.25.5"
default-features = false
features = ["png", "jpeg"]
