[package]
name = "farm-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.22.0", features = ["derive"]}
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"

[dependencies.image]
version = "0.25.5"
default-features = false
features = ["png", "jpeg"]
