[package]
name = "farm-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.23.1", features = ["derive"]}
pollster = "0.4.0"
wgpu = "25.0.2"
winit = "0.30.11"

[dependencies.image]
version = "0.25.6"
default-features = false
features = ["png", "jpeg"]
