[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
pollster = "0.4.0"
wgpu = "26.0.1"
winit = "0.30.12"
